# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- import_tasks: 'package.yml'
  tags:
    - 'packages'
    - 'packages-package'
    - 'package'